# Generated by Django 5.0.6 on 2024-08-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solvent', models.BooleanField(default=False, null=True)),
                ('cylinder', models.BooleanField(default=False, null=True)),
                ('rubberRoller', models.BooleanField(db_column='rubberRoller', default=False, null=True)),
                ('drBlade', models.BooleanField(db_column='drBlade', default=False, null=True)),
                ('rawMaterial', models.BooleanField(db_column='rawMaterial', default=False, null=True)),
                ('mcSurroundings', models.BooleanField(db_column='mcSurroundings', default=False, null=True)),
                ('wasteMatl', models.BooleanField(db_column='wasteMatl', default=False, null=True)),
                ('printedMatl', models.BooleanField(db_column='printedMatl', default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unwinder1', models.CharField(max_length=255, null=True)),
                ('unwinder2', models.CharField(max_length=255, null=True)),
                ('rewinder', models.CharField(max_length=255, null=True)),
                ('coatingTemp', models.CharField(db_column='coatingTemp', max_length=255, null=True)),
                ('nipTemp', models.CharField(db_column='nipTemp', max_length=255, null=True)),
                ('ncoTemp', models.CharField(db_column='ncoTemp', max_length=255, null=True)),
                ('ohTemp', models.CharField(db_column='ohTemp', max_length=255, null=True)),
                ('coaterCurrent', models.CharField(blank=True, db_column='coaterCurrent', max_length=255, null=True)),
                ('nipPressure', models.CharField(db_column='nipPressure', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NcoAndOh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(db_column='supplier', max_length=255, null=True)),
                ('grade', models.CharField(db_column='grade', max_length=255, null=True)),
                ('bathNo', models.CharField(db_column='bathNo', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolyWastageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.CharField(max_length=255, null=True)),
                ('wrinkle', models.CharField(max_length=255, null=True)),
                ('coreEnd', models.CharField(db_column='coreEnd', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printedRollNo', models.CharField(db_column='printedRollNo', max_length=255, null=True)),
                ('printingOpName', models.CharField(db_column='printingOpName', max_length=255, null=True)),
                ('printedInputRollKgs', models.CharField(db_column='printedInputRollKgs', max_length=255, null=True)),
                ('supName', models.CharField(db_column='supName', max_length=255, null=True)),
                ('supRollNo', models.CharField(db_column='supRollNo', max_length=255, null=True)),
                ('netWt', models.CharField(db_column='netWt', max_length=255, null=True)),
                ('outputRollNo', models.CharField(db_column='outputRollNo', max_length=255, null=True)),
                ('outputRollWtKgs', models.CharField(db_column='outputRollWtKgs', max_length=255, null=True)),
                ('outputRollMtrs', models.CharField(db_column='outputRollMtrs', max_length=255, null=True)),
                ('startingTime', models.CharField(db_column='startingTime', max_length=255, null=True)),
                ('endTime', models.CharField(db_column='endTime', max_length=255, null=True)),
                ('adhGsm', models.CharField(db_column='adhGsm', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plainPEWastage', models.CharField(db_column='plainPEWastage', max_length=255, null=True)),
                ('printedWastage', models.CharField(db_column='printedWastage', max_length=255, null=True)),
                ('packingWaste', models.CharField(db_column='packingWaste', max_length=255, null=True)),
                ('laminationWaste', models.CharField(db_column='laminationWaste', max_length=255, null=True)),
                ('total', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=50)),
                ('empId', models.CharField(default='M1372', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('pause', models.BooleanField(default=False)),
                ('reset_token', models.CharField(max_length=1000, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255, null=True)),
                ('nco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_nco', to='app.ncoandoh')),
                ('oh', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_oh', to='app.ncoandoh')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slNo', models.CharField(db_column='slNo', max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('mc', models.CharField(max_length=255, null=True)),
                ('input', models.CharField(max_length=255, null=True)),
                ('returnMaterial', models.CharField(db_column='return', max_length=255, null=True)),
                ('used', models.CharField(max_length=255, null=True)),
                ('lineClearance', models.CharField(db_column='lineClearance', max_length=255, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('grade', models.CharField(max_length=255, null=True)),
                ('bathNo', models.CharField(max_length=255, null=True)),
                ('ratio', models.CharField(blank=True, max_length=255, null=True)),
                ('inputQty', models.CharField(blank=True, db_column='inputQty', max_length=255, null=True)),
                ('rawMaterial', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workOrderNo', models.CharField(max_length=255, null=True)),
                ('customer', models.CharField(max_length=255, null=True)),
                ('jobName', models.CharField(db_column='jobName', max_length=255, null=True)),
                ('sleeveSize', models.CharField(db_column='sleeveSize', max_length=255, null=True)),
                ('target', models.CharField(max_length=255, null=True)),
                ('produced', models.CharField(max_length=255, null=True)),
                ('balance', models.CharField(max_length=255, null=True)),
                ('operatorName', models.CharField(db_column='operatorName', max_length=255, null=True)),
                ('assistantName', models.CharField(db_column='assistantName', max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('mcName', models.CharField(db_column='mcName', max_length=255, null=True)),
                ('shift', models.CharField(max_length=255, null=True)),
                ('mcSpeed', models.CharField(max_length=255, null=True)),
                ('productionWeight', models.CharField(max_length=255, null=True)),
                ('dyanLevel', models.CharField(max_length=255, null=True)),
                ('ProductionDetails', models.ManyToManyField(null=True, to='app.productiondetail')),
                ('lineClearance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lineclearance')),
                ('machineParameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.machineparameter')),
                ('materialDetails', models.ManyToManyField(null=True, to='app.materialdetail')),
                ('polyWastageDetails', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.polywastagedetail')),
                ('scrapDetails', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.scrapdetail')),
            ],
        ),
    ]
