# Generated by Django 5.0.6 on 2024-08-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakDownDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeveChange', models.CharField(db_column='sleeveChange', max_length=255, null=True)),
                ('cleaning', models.CharField(db_column='cleaning', max_length=255, null=True)),
                ('totalProdnMin', models.CharField(db_column='totalProdnMin', max_length=255, null=True)),
                ('jobSettingMin', models.CharField(db_column='jobSettingMin', max_length=255, null=True)),
                ('rollChangeMin', models.CharField(db_column='rollChangeMin', max_length=255, null=True)),
                ('noPlanning', models.CharField(db_column='noPlanning', max_length=255, null=True)),
                ('breakDownMin', models.CharField(db_column='breakDownMin', max_length=255, null=True)),
                ('powerCut', models.CharField(db_column='powerCut', max_length=255, null=True)),
                ('tagRemove', models.CharField(db_column='tagRemove', max_length=255, null=True)),
                ('total', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workorderheader',
            name='breakDownDetail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.breakdowndetail'),
        ),
    ]
